name: ipfs_app
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  http: ^1.4.0
  file_picker: ^10.1.7
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  crypto: ^3.0.6
  fl_chart: ^0.71.0
  device_info_plus: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true


